---
title: "Math 300 Lesson 21 Notes"
subtitle: "Case Study"
author: "YOUR NAME HERE"
date: "`r format(Sys.time(), '%B, %Y')`"
output:
  pdf_document:
    toc: yes
  html_document:
    theme: lumen
    toc: yes
    toc_float: yes
    css: NTI.css
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Objectives

1. Given a sampling scenario, discuss issues such as accuracy and precision as they relate to generalization to the population of interest.

## Reading 

[Chapter 7.4](https://moderndive.com/7-sampling.html#sampling-case-study)

## Lesson 

Work through the learning checks LC7.21 - 7.24.


Comment on the representativeness of the following *sampling methodologies*:

### LC 7.21 (Objective 1)

**(LC 7.21)** The Royal Air Force wants to study how resistant all their airplanes are to bullets. They study the bullet holes on all the airplanes on the tarmac after an air battle against the Luftwaffe (German Air Force).

**Solution**:



### LC 7.22 (Objective 1)

**(LC 7.22)** Imagine it is 1993, a time when almost all households had landlines. You want to know the average number of people in each household in your city. You randomly pick out 500 phone numbers from the phone book and conduct a phone survey.

**Solution**:


### LC 7.23 (Objective 1)

**(LC 7.23)** You want to know the prevalence of illegal downloading of TV shows among students at a local college.  You get the emails of 100 randomly chosen students and ask them, "How many times did you download a pirated TV show last week?".

**Solution**:


### LC 7.24 (Objective 1)

**(LC 7.24)** A local college administrator wants to know the average income of all graduates in the last 10 years. So they get the records of five randomly chosen graduates, contact them, and obtain their answers. 

**Solution**:


## Documenting software 

  * File creation date: `r Sys.Date()`
  * `r R.version.string`
  * `tidyverse` package version: `r packageVersion("tidyverse")`
  * `moderndive` package version: `r packageVersion("moderndive")`
